[files]
extend-exclude = [
  "",
  "crates/fastwebsockets",
  "crates/yawc/benches",
  "crates/hpx-util/src/emulation",
  "crates/hpx/tests/badssl.rs",
]

[default.extend-words]
Divy = "Divy"
divy = "divy"
WRK = "WRK"
EDE = "EDE"
